name: Dummy Workflow

on: push 


jobs:
  dummy-job:
    runs-on: ubuntu-latest

    steps:
      - name: My first work flow 
        run : echo "Hello from GitHub Actions!"

      - name: listing files
        run: ls -lrth

      - name: checking the readme.md file
        run: cat README.md

