name: Dummy Workflow

on: push 


jobs:
  dummy-job:
    runs-on: ubuntu-latest

    steps:
      - name: My first work flow 
        run : echo "Hello from GitHub Actions!"

      - name: listing files
        run: ls -lrth

      - name: checkout repo
        uses: actions/checkout@v6

      - name: executing mutilples commands 
        run: |
         echo "Running mutiple commands"
         cat README.md

      - name: Insttal cowsay lib
        run: sudo apt install cowsay -y  

      - name: run cowsay lib 
        run: cowsay -f dragon "Run for the cover" >> dragon.txt

